### ISSUE TITLE
Multiplication order of vector and matrix matters.

### ISSUE THREAD

**Issue by sol-vin** [mathalaxy/vectormath#4]
When using this code there is a major error
```crystal
v = VM::Vec3.one
m = VM::Mat3f.identity
puts m*v # works great
puts v*m # Throws error
```
Causes error:
```
Showing last frame. Use --error-trace for full trace.

In /usr/share/crystal/src/float.cr:135:11

 135 | value.to_f32
             ^-----
Error: undefined method 'to_f32' for VM::Mat3x3(Float32)
```

Inviting you to use --error-trace. Doing this will flood the console with over 500k lines of macros and generally be unhelpful in debugging this.

**Comment by feritarou** [comment]
The multiplication order in matrix multiplication _actually_ matters. A `VM::Vec` represents a column vector, following standard mathematical convention, and according to the rules of matrix multiplication it is not possible to right-multiply a single column with anything except a scalar. Thus what you are describing is intended behavior, rather than a bug.

I admit, though, that the error messages are very unhelpful and in this case even misleading. I will try to improve that in a future version, but Crystal's way of reporting errors within macros is a problem here. 

Regarding your code sample I think altering the behavior so that `v*m` were just accepted would be a bad idea. What _is_ needed for use cases like yours is a _transpose_ method `VecX#t` which (in analogy to `MatX#t`) would convert a column vector into a single-row matrix `Mat1xX`, and permit you to write `v.t * m` resulting in another `Mat1xX` "row vector". Next time I get back to the API I'll add that method; until then you can use
```
w = mat1x3f(*v.xyz)
puts w*m
```
as a workaround.

**Comment by sol-vin** [comment]
My bad I didn't know about the order mattering, I'm still new to vector math. The macro thing was just a very difficult bug because it's hard to find out what I did wrong. Thanks for taking the time to explain everything to me in detail. Luckily I don't need to order them in an particular way, so swapping works fine.
